# Generated by Django 5.1.4 on 2026-05-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bnpl_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tamara/Tabby service fee. 0 for COD.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('UAE', 'United Arab Emirates'), ('KSA', 'Saudi Arabia')], default='UAE', help_text='Determines shipping fee and which provider keys/URLs are used.', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='subtotal + shipping_fee + bnpl_surcharge', max_digits=10),
        ),
    ]
