# Generated by Django 5.1.4 on 2026-06-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_bnpl_surcharge_order_region_order_shipping_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Coupon code applied at checkout, if any.', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='AED discount applied from coupon_code.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='bnpl_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy field. Always 0 — BNPL surcharge was removed.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='subtotal + shipping_fee - discount_amount', max_digits=10),
        ),
    ]
