# Generated by Django 5.1.4 on 2026-07-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_coupon_code_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('card', 'Card / Apple Pay / Google Pay'), ('tamara', 'Tamara'), ('tabby', 'Tabby')], default='cod', max_length=16),
        ),
    ]
