# Generated by Django 5.1.4 on 2026-04-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_setting_options_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='button_ar',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='desc_ar',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
