# Generated by Django 5.1.4 on 2026-06-04 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_stockmovement'),
        ('orders', '0003_order_coupon_code_order_discount_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Customer types this at checkout. Case-insensitive. e.g. WELCOME10', max_length=32, unique=True)),
                ('description', models.CharField(blank=True, help_text='Internal note — not shown to customers.', max_length=200)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage off'), ('fixed', 'Fixed amount off (AED)')], default='percent', max_length=16)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text="For 'percent': enter 10 for 10%. For 'fixed': enter 50 for AED 50 off.", max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional cap on percent discounts. Leave blank for no cap.', max_digits=10, null=True)),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Cart subtotal must be at least this much. 0 = no minimum.', max_digits=10)),
                ('region_scope', models.CharField(choices=[('BOTH', 'Both UAE & KSA'), ('UAE', 'UAE only'), ('KSA', 'KSA only')], default='BOTH', max_length=4)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Max total uses across all customers. Leave blank for unlimited.', null=True)),
                ('used_count', models.PositiveIntegerField(default=0, editable=False)),
                ('per_user_limit', models.PositiveIntegerField(default=1, help_text='Max times one logged-in customer can use this code. 0 = unlimited.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to_brands', models.ManyToManyField(blank=True, help_text='Restrict to these brands. Leave empty to apply to all.', related_name='coupons', to='catalog.brand')),
                ('applies_to_categories', models.ManyToManyField(blank=True, help_text='Restrict to these categories. Leave empty to apply to all.', related_name='coupons', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='coupons.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
